name: chess_rps
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_hooks: ^0.20.1
  hooks_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  stockfish: ^1.4.0
  stockfish_interpreter:
    path: ../stockfish_interpreter

  mockito: ^5.4.2
  riverpod_test: ^0.1.3
  melos: ^3.1.1

  dio: ^5.3.3
  web_socket_channel: ^2.4.0
  flutter_secure_storage: ^9.0.0
  go_router: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.0.4
  flutter_lints: ^2.0.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/figures/ancient/white/
    - assets/images/figures/ancient/black/
    - assets/images/figures/california/white/
    - assets/images/figures/california/black/
    - assets/images/figures/cardinal/white/
    - assets/images/figures/cardinal/black/
    - assets/images/figures/celtic/white/
    - assets/images/figures/celtic/black/
    - assets/images/figures/condal/white/
    - assets/images/figures/condal/black/
    - assets/images/figures/metal/white/
    - assets/images/figures/metal/black/
    - assets/images/figures/modern/white/
    - assets/images/figures/modern/black/
    - assets/images/figures/stone/white/
    - assets/images/figures/stone/black/
    - assets/images/figures/tournament/white/
    - assets/images/figures/tournament/black/
    - assets/images/figures/vintage/white/
    - assets/images/figures/vintage/black/
    - assets/images/figures/wood/white/
    - assets/images/figures/wood/black/
